#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/11/05 13:45:22 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/SoccerBots/Docs
SUBDIRS = images

include ../../../Makefile.src
