#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:27:59 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/gatech/cc/is/abstractrobot
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../../../../../Makefile.src
