#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/07 21:05:09 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = lib/Serialio
SUBDIRS = Lib
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
