#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/11/05 13:46:09 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/SoccerBots/Docs/images
SUBDIRS = 

include ../../../../Makefile.src
