#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/07 23:23:29 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/biology/ants
SUBDIRS = 
#JAVAFILES = $(shell echo *.java)

include ../../../../../Makefile.src
