#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:29:13 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/gatech
SUBDIRS = cc
JAVAFILES = 

include ../../../Makefile.src
