#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:29:42 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/biology
SUBDIRS = ants
JAVAFILES = 

include ../../../../Makefile.src
