#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 1999/11/04 17:36:34 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Book/Docs
SUBDIRS = Images
JAVAFILES =

include ../../../Makefile.src
