#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:27:42 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/gatech/cc
SUBDIRS = is
JAVAFILES = 

include ../../../../Makefile.src
