#
# $RCSfile: Makefile,v $
# $Revision: 1.4 $
# $Date: 2000/03/07 20:29:41 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu
SUBDIRS = biology cs
JAVAFILES = 

include ../../../Makefile.src
