#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 2000/03/06 16:23:59 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/CyeSoccer
SUBDIRS = 
JAVAFILES := $(shell echo *.java)

include ../../Makefile.src
