#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 2000/03/12 23:25:42 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Network
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
