#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/08 00:26:47 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = lib/Serialio/Lib/Aix
SUBDIRS = 

JAVAFILES = 

include ../../../../Makefile.src
