#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/12/13 15:57:18 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Cye
SUBDIRS = 
JAVAFILES := $(shell echo *.java)

include ../../Makefile.src
