#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/11/04 17:59:41 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Roads
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
