#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/04/14 23:00:27 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/cs/coral/clay
SUBDIRS = 
#
#uncomment when there are some files here
#JAVAFILES = $(shell echo *.java)

include ../../../../../../Makefile.src
