#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/07 20:44:43 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/RoboComm
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
