#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 1999/11/04 17:36:36 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Book/Docs/Images
SUBDIRS = 
JAVAFILES = 

include ../../../../Makefile.src
