#
# $RCSfile: Makefile,v $
# $Revision: 1.8 $
# $Date: 2000/03/29 16:11:42 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/cs/coral
SUBDIRS = abstractrobot clay cmvision cye learning localize simulation util
JAVAFILES = 

include ../../../../../Makefile.src
