#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 21:05:13 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = lib/Serialio/Lib/HpUx
SUBDIRS = 

JAVAFILES = 

include ../../../../Makefile.src
