#
# $RCSfile: Makefile,v $
# $Revision: 1.4 $
# $Date: 1999/11/05 16:16:44 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/SoccerBots/teams
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../../Makefile.src
