#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/07 21:20:19 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/CMVision
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
include Makefile.src
