#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:52:08 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/TBSim
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
