#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 1999/11/05 16:16:43 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Book
SUBDIRS = Docs
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
