#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 21:05:10 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = lib/Serialio/Lib
SUBDIRS = Aix HpUx Linux Os2 Solx86 Bsd Irix Mac SolSparc Win32

JAVAFILES = 

include ../../../Makefile.src
