#
# $RCSfile: Makefile,v $
# $Revision: 1.4 $
# $Date: 2000/03/07 20:27:54 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/gatech/cc/is
SUBDIRS = abstractrobot clay communication learning newton nomad150 simulation util
JAVAFILES = 

include ../../../../../Makefile.src
