#
# $RCSfile: Makefile,v $
# $Revision: 1.3 $
# $Date: 2000/03/07 20:29:52 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/cs/coral/localize
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../../../../../Makefile.src
