#
# $RCSfile: Makefile,v $
# $Revision: 1.10 $
# $Date: 2000/03/07 20:57:50 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src
SUBDIRS = EDU CMVision JCye RoboComm TBSim TBHard
JAVAFILES = 

include ../Makefile.src
