#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/11/04 17:57:48 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/ForageAAAI97
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../Makefile.src
