#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:29:44 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/cs
SUBDIRS = coral
JAVAFILES = 

include ../../../../Makefile.src
