#
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2000/03/07 20:29:51 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = src/EDU/cmu/cs/coral/learning
SUBDIRS = 
JAVAFILES = $(shell echo *.java)

include ../../../../../../Makefile.src
